clang compiles... missing ar and other tools

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -21,12 +21,12 @@
 #
 usage()
 {
-	echo "Usage: $0 [--build=BUILD] [--host=HOST] [--prefix=PREFIX]"
-	echo "  --build=BUILD    configure for building on BUILD"
-	echo "  --host=HOST      cross-compile to build to run on HOST"
-	echo "  --prefix=PREFIX  install files in PREFIX"
-	echo "  --disable-FOO    configure to not build package FOO"
-	echo "  --enable-FOO     configure to build package FOO"
+    echo "Usage: $0 [--build=BUILD] [--host=HOST] [--prefix=PREFIX]"
+    echo "  --build=BUILD    configure for building on BUILD"
+    echo "  --host=HOST      cross-compile to build to run on HOST"
+    echo "  --prefix=PREFIX  install files in PREFIX"
+    echo "  --disable-FOO    configure to not build package FOO"
+    echo "  --enable-FOO     configure to build package FOO"
 }
 
 BUILD=
@@ -37,63 +37,63 @@ PKGS_DISABLE=
 
 if test ! -f "../../contrib/src/main.mak"
 then
-	echo "$0 must be run from a subdirectory"
-	exit 1
+    echo "$0 must be run from a subdirectory"
+    exit 1
 fi
 
 while test -n "$1"
 do
-	case "$1" in
-		--build=*)
-			BUILD="${1#--build=}"
-			;;
-		--help|-h)
-			usage
-			exit 0
-			;;
-		--host=*)
-			HOST="${1#--host=}"
-			;;
-		--prefix=*)
-			PREFIX="${1#--prefix=}"
-			;;
-		--disable-*)
-			PKGS_DISABLE="${PKGS_DISABLE} ${1#--disable-}"
-			;;
-		--enable-*)
-			PKGS_ENABLE="${PKGS_ENABLE} ${1#--enable-}"
-			;;
-		*)
-			echo "Unrecognized options $1"
-			usage
-			exit 1
-			;;
-	esac
-	shift
+    case "$1" in
+        --build=*)
+            BUILD="${1#--build=}"
+            ;;
+        --help|-h)
+            usage
+            exit 0
+            ;;
+        --host=*)
+            HOST="${1#--host=}"
+            ;;
+        --prefix=*)
+            PREFIX="${1#--prefix=}"
+            ;;
+        --disable-*)
+            PKGS_DISABLE="${PKGS_DISABLE} ${1#--disable-}"
+            ;;
+        --enable-*)
+            PKGS_ENABLE="${PKGS_ENABLE} ${1#--enable-}"
+            ;;
+        *)
+            echo "Unrecognized options $1"
+            usage
+            exit 1
+            ;;
+    esac
+    shift
 done
 
 if test -z "$BUILD"
 then
-	echo -n "Guessing build system... "
-	BUILD="`${CC:-cc} -dumpmachine`"
-	if test -z "$BUILD"; then
-		echo "FAIL!"
-		exit 1
-	fi
-	echo "$BUILD"
+    echo -n "Guessing build system... "
+    BUILD="`${CC:-cc} -dumpmachine`"
+    if test -z "$BUILD"; then
+        echo "FAIL!"
+        exit 1
+    fi
+    echo "$BUILD"
 fi
 
 if test -z "$HOST"
 then
-	echo -n "Guessing host system...  "
-	HOST="$BUILD"
-	echo "$HOST"
+    echo -n "Guessing host system...  "
+    HOST="$BUILD"
+    echo "$HOST"
 fi
 
 if test "$PREFIX"
 then
-	# strip trailing slash
-	PREFIX="${PREFIX%/}"
+    # strip trailing slash
+    PREFIX="${PREFIX%/}"
 fi
 
 #
@@ -112,20 +112,20 @@ EOF
 
 add_make()
 {
-	while test -n "$1"
-	do
-		echo "$1" >&3
-		shift
-	done
+    while test -n "$1"
+    do
+        echo "$1" >&3
+        shift
+    done
 }
 
 add_make_enabled()
 {
-	while test -n "$1"
-	do
-		add_make "$1 := 1"
-		shift
-	done
+    while test -n "$1"
+    do
+        add_make "$1 := 1"
+        shift
+    done
 }
 
 check_tvos_sdk()
@@ -262,84 +262,83 @@ check_macosx_sdk()
 
 check_android_sdk()
 {
-        ANDROID_ABI=$MY_TARGET_ARCH
+    ANDROID_ABI=$MY_TARGET_ARCH
+
+    [ -z "${ANDROID_NDK}" ] && echo "You must set ANDROID_NDK environment variable" && exit 1
+    add_make "ANDROID_NDK := ${ANDROID_NDK}"
+    [ -z "${ANDROID_ABI}" ] && echo "You must set ANDROID_ABI environment variable" && exit 1
+    add_make "ANDROID_ABI := ${ANDROID_ABI}"
+    [ -z "${ANDROID_API}" ] && echo "You should set ANDROID_API environment variable (using default android-9)" && ANDROID_API := android-9
+    add_make "ANDROID_API := ${ANDROID_API}"
+    
+    ## FIXME: the android toolchain path is hardcoded, only MACOSX will work.
+    if [ ${ANDROID_ABI} = "x86" ]; then
+        add_make "ANDROID_LLVM_TARGET := i686-none-linux-android"
+    elif [ ${ANDROID_ABI} = "arm64-v8a" ];then
+        add_make "ANDROID_LLVM_TARGET := aarch64-none-linux-android"
+    elif [ ${ANDROID_ABI} = "armeabi-v7a" ];then
+        add_make "ANDROID_LLVM_TARGET := armv7-none-linux-androideabi"
+    elif [ ${ANDROID_ABI} = "armeabi" ];then
+        add_make "ANDROID_LLVM_TARGET := armv5te-none-linux-androideabi"
+    elif [ ${ANDROID_ABI} = "mips" ];then
+        add_make "ANDROID_LLVM_TARGET := mipsel-none-linux-android"
+    else
+        echo "${ANDROID_ABI}: Invalid arch for Android. Valid archs: x86, arm64, armv7, arm, mips"
+        exit 1
+    fi
+
+    # check whether sysroot is exists
+    if [ $ANDROID_ABI = "arm64" ]; then
+        if [ ! -d ${ANDROID_NDK}/platforms/${ANDROID_API}/arch-arm64 ];then
+            echo "${ANDROID_NDK} ${ANDROID_API} doesn't support build arm64 architecture! Set ANDROID_API to 21 or higher"
+            exit $? 
+        fi
+    fi
+    
+    # check whether cc exists
+    if [ ! -d ${ANDROID_NDK}/toolchains/llvm ] ;then
+        echo "${ANDROID_NDK} Android llvm toolchain not found. Make sure that NDK >= r11 is installed!"
+        exit 1
+    fi
+
+    add_make "ANDROID_LLVM_PATH := ${ANDROID_NDK}/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"
+
+    THUMB_FLAG=""
+    if [ $ANDROID_USE_MTHUMB = "yes" ];then
+        THUMB_FLAG="-mthumb"
+        echo "we are using mthumb for ${ANDROID_ABI}!!"
+    fi
+
+
+    if [ ${ANDROID_ABI} = "armeabi-v7a" ]; then
+        add_make_enabled "HAVE_NEON"
+        add_make_enabled "HAVE_ARMV7A"
+        add_make "EXTRA_CFLAGS := -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 ${THUMB_FLAG} -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
+        add_make "EXTRA_LDFLAGS := -march=armv7-a -Wl,--fix-cortex-a8"
+    fi
         
-	[ -z "${ANDROID_NDK}" ] && echo "You must set ANDROID_NDK environment variable" && exit 1
-	add_make "ANDROID_NDK := ${ANDROID_NDK}"
-	[ -z "${ANDROID_GCC_VERSION}" ] && echo "You must set ANDROID_GCC_VERSION environment variable" && exit 1
-	add_make "ANDROID_GCC_VERSION := ${ANDROID_GCC_VERSION}"
-	[ -z "${ANDROID_ABI}" ] && echo "You must set ANDROID_ABI environment variable" && exit 1
-	add_make "ANDROID_ABI := ${ANDROID_ABI}"
-	[ -z "${ANDROID_API}" ] && echo "You should set ANDROID_API environment variable (using default android-9)" && ANDROID_API := android-9
-	add_make "ANDROID_API := ${ANDROID_API}"
-        
-        ## FIXME: the android toolchain path is hardcoded, only MACOSX will work.
-        if [ ${ANDROID_ABI} = "x86" ]; then
-            toolchain_path_prefix="i686-none-linux-android"
-        elif [ ${ANDROID_ABI} = "arm64" ];then
-            toolchain_path_prefix="aarch64-none-linux-android"
-        elif [ ${ANDROID_ABI} = "armv7" ];then
-            toolchain_path_prefix="armv7-none-linux-androideabi"
-        elif [ ${ANDROID_ABI} = "arm" ];then
-            toolchain_path_prefix="armv5te-none-linux-androideabi"
-        elif [ ${ANDROID_ABI} = "mips" ];then
-            toolchain_path_prefix="mipsel-none-linux-android"
-        else
-            echo "${ANDROID_ABI}: Invalid arch for Android. Valid archs: x86, arm64, armv7, arm, mips"
-            exit 1
-        fi
+    if [ ${ANDROID_ABI} = "armeabi" -a -z "${NO_ARMV6}" ];then
+        add_make_enabled "HAVE_ARMV6"
+        add_make "EXTRA_CFLAGS := -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes  -march=armv5te -mtune=xscale -msoft-float ${THUMB_FLAG} -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
+    fi
 
-        # check whether sysroot is exists
-        if [ $ANDROID_ABI = "arm64-v8a" ]; then
-            if [ ! -d ${ANDROID_NDK}/platforms/${ANDROID_API}/arch-arm64 ];then
-                echo "${ANDROID_NDK} ${ANDROID_API} doesn't support build arm64 architecture!"
-                exit $? 
-            fi
-        fi
-        
-        # check whether gcc version is exists
-        if [ ! -d ${ANDROID_NDK}/toolchains/${toolchain_path_prefix}-${ANDROID_GCC_VERSION} ] ;then
-            echo "${ANDROID_NDK} Invalid GCC ${ANDROID_GCC_VERSION} version!"
-            exit 1
-        fi
+    if [ ${ANDROID_ABI} = "arm64-v8a" ]; then
+        add_make_enabled "HAVE_NEON"
+        add_make_enabled "HAVE_ARMV8A"
+        add_make "EXTRA_CFLAGS :=  -fpic -ffunction-sections  -funwind-tables  -fstack-protector  -no-canonical-prefixes"
+        add_make "EXTRA_LDFLAGS := -no-canonical-prefixes"
+    fi
 
-        THUMB_FLAG=""
-        if [ $ANDROID_USE_MTHUMB = "yes" ];then
-            THUMB_FLAG="-mthumb"
-            echo "we are using mthumb for ${ANDROID_ABI}!!"
-        fi
+    if [ ${ANDROID_ABI} = "x86" ];then
+        add_make_enabled "HAVE_x86"
+        add_make "EXTRA_CFLAGS := -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes  -fomit-frame-pointer -fstrict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
+    fi
 
-
-	if [ ${ANDROID_ABI} = "armeabi-v7a" ]; then
-            add_make_enabled "HAVE_NEON"
-            add_make_enabled "HAVE_ARMV7A"
-            add_make "EXTRA_CFLAGS := -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 ${THUMB_FLAG} -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
-            add_make "EXTRA_LDFLAGS := -march=armv7-a -Wl,--fix-cortex-a8"
-        fi
-        
-	if [ ${ANDROID_ABI} = "armeabi" -a -z "${NO_ARMV6}" ];then
-            add_make_enabled "HAVE_ARMV6"
-            add_make "EXTRA_CFLAGS := -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes  -march=armv5te -mtune=xscale -msoft-float ${THUMB_FLAG} -fomit-frame-pointer -fno-strict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
-        fi
-
-	if [ ${ANDROID_ABI} = "arm64-v8a" ]; then
-            add_make_enabled "HAVE_NEON"
-            add_make_enabled "HAVE_ARMV8A"
-            add_make "EXTRA_CFLAGS :=  -fpic -ffunction-sections  -funwind-tables  -fstack-protector  -no-canonical-prefixes"
-            add_make "EXTRA_LDFLAGS := -no-canonical-prefixes"
-        fi
-
-        if [ ${ANDROID_ABI} = "x86" ];then
-            add_make_enabled "HAVE_x86"
-            add_make "EXTRA_CFLAGS := -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes  -fomit-frame-pointer -fstrict-aliasing -DANDROID  -Wa,--noexecstack -Wformat "
-        fi
-
-        if [ ${ANDROID_STL_VERSION} = "gnu" ];then
-            add_make_enabled "HAVE_STL_GUN"
-        else
-            add_make_enabled "HAVE_STL_CLANG"
-        fi
-        
+    if [ ${ANDROID_STL_VERSION} = "gnu" ];then
+        add_make_enabled "HAVE_STL_GUN"
+    else
+        add_make_enabled "HAVE_STL_CLANG"
+    fi
 }
 
 check_tizen_sdk()
@@ -356,59 +355,59 @@ test -z "$PREFIX" || add_make "PREFIX := $PREFIX"
 OS="${HOST#*-}" # strip architecture
 echo "The host is $OS"
 case "${OS}" in
-	apple-darwin*)
-		if test -n "$BUILDFORIOS"
-		then
-			check_ios_sdk
-			add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD"  "HAVE_ARMV7A" "HAVE_NEON"
-		elif test -n "$BUILDFORTVOS"
-		then
-			check_tvos_sdk
-			add_make_enabled "HAVE_TVOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_NEON"
-		else
-			check_macosx_sdk
-			add_make_enabled "HAVE_MACOSX" "HAVE_DARWIN_OS" "HAVE_BSD"
-		fi
-		;;
-	*bsd*)
-		add_make_enabled "HAVE_BSD"
-		;;
-	*android*)
+    apple-darwin*)
+        if test -n "$BUILDFORIOS"
+        then
+            check_ios_sdk
+            add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD"  "HAVE_ARMV7A" "HAVE_NEON"
+        elif test -n "$BUILDFORTVOS"
+        then
+            check_tvos_sdk
+            add_make_enabled "HAVE_TVOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_NEON"
+        else
+            check_macosx_sdk
+            add_make_enabled "HAVE_MACOSX" "HAVE_DARWIN_OS" "HAVE_BSD"
+        fi
+        ;;
+    *bsd*)
+        add_make_enabled "HAVE_BSD"
+        ;;
+    *android*)
                 echo "check android sdk"
-		check_android_sdk
-		add_make_enabled "HAVE_LINUX" "HAVE_ANDROID"
-		case "${HOST}" in
-			*arm*)
-			    add_make "PLATFORM_SHORT_ARCH := arm"
-			;;
-			*arm64* | *aarch64*)
-			    add_make "PLATFORM_SHORT_ARCH := arm64"
-			;;
-			*i686*)
-			    add_make "PLATFORM_SHORT_ARCH := x86"
-			;;
-			*x86_64*)
-			    add_make "PLATFORM_SHORT_ARCH := x86_64"
-			;;
-			*mipsel*)
-			    add_make "PLATFORM_SHORT_ARCH := mips"
-			;;
-		esac
-		;;
+        check_android_sdk
+        add_make_enabled "HAVE_LINUX" "HAVE_ANDROID"
+        case "${HOST}" in
+            *arm*)
+                add_make "PLATFORM_SHORT_ARCH := arm"
+            ;;
+            *arm64* | *aarch64*)
+                add_make "PLATFORM_SHORT_ARCH := arm64"
+            ;;
+            *i686*)
+                add_make "PLATFORM_SHORT_ARCH := x86"
+            ;;
+            *x86_64*)
+                add_make "PLATFORM_SHORT_ARCH := x86_64"
+            ;;
+            *mipsel*)
+                add_make "PLATFORM_SHORT_ARCH := mips"
+            ;;
+        esac
+        ;;
         *gnueabi*)
             echo "check Tizen SDK"
             check_tizen_sdk
             add_make_enabled "HAVE_TIZEN" "HAVE_LINUX"
             ;;
-	*linux*)
-		add_make_enabled "HAVE_LINUX"
-		;;
-	*mingw*)
-		add_make_enabled "HAVE_WIN32"
-		;;
-	*solaris*)
-		add_make_enabled "HAVE_SOLARIS"
-		;;
+    *linux*)
+        add_make_enabled "HAVE_LINUX"
+        ;;
+    *mingw*)
+        add_make_enabled "HAVE_WIN32"
+        ;;
+    *solaris*)
+        add_make_enabled "HAVE_SOLARIS"
+        ;;
 esac
 
 #
