clang for android

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -275,11 +275,18 @@ check_android_sdk()
         
         ## FIXME: the android toolchain path is hardcoded, only MACOSX will work.
         if [ ${ANDROID_ABI} = "x86" ]; then
-            toolchain_path_prefix=x86
-        elif [ ${ANDROID_ABI} = "arm64-v8a" ];then
-            toolchain_path_prefix=aarch64-linux-android
+            toolchain_path_prefix="i686-none-linux-android"
+        elif [ ${ANDROID_ABI} = "arm64" ];then
+            toolchain_path_prefix="aarch64-none-linux-android"
+        elif [ ${ANDROID_ABI} = "armv7" ];then
+            toolchain_path_prefix="armv7-none-linux-androideabi"
+        elif [ ${ANDROID_ABI} = "arm" ];then
+            toolchain_path_prefix="armv5te-none-linux-androideabi"
+        elif [ ${ANDROID_ABI} = "mips" ];then
+            toolchain_path_prefix="mipsel-none-linux-android"
         else
-            toolchain_path_prefix=arm-linux-androideabi
+            echo "${ANDROID_ABI}: Invalid arch for Android. Valid archs: x86, arm64, armv7, arm, mips"
+            exit 1
         fi
 
         # check whether sysroot is exists
